
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: 'jdbc:h2:mem:testdb'
    username: 'sa'
    password: ''
    driver-class-name: org.h2.Driver
    schema: 'classpath:acl-schema.sql'
    data: 'classpath:acl-data.sql'




